# Generated by Django 2.2.4 on 2020-09-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPartTwoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='endDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
