# Generated by Django 2.2.4 on 2020-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPartTwoApp', '0002_auto_20200923_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='endDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
